'use client'
import { Lexend } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import { Toaster } from 'react-hot-toast';
import { BsFacebook, BsLinkedin, BsTwitter } from 'react-icons/bs';
import '../styles/globals.css';
import { useState } from 'react';

const inter = Lexend({ subsets: ['latin'] })

const metadata = {
  title: 'Open Word - Landing Page',
  description: 'Generated by create next app',
};

const links = [
  { label: 'Inicio', route: '/' },
  { label: 'Sobre nosotros', route: '/about' },
  { label: 'Estado de cuenta', route: '/account-status' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [isNavOpen, setIsNavOpen] = useState(false);

  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body className={`${inter.className} min-h-screen`}>
        <header className='border-b border-gray-900/10 pt-0 pb-0 bg-[#1f1f1f]'>
          <Link href={'/'} className='flex items-center'>
            <Image
              src='/images/logo.png'
              alt='OpenWod Logo'
              width={100}
              height={100}
            />
            <h4 className='text-[#e7ae0a] hidden md:block'>OpenWord</h4>
          </Link>
          <nav>
            <ul className='hidden md:flex gap-5 text-white'>
              {links.map(({ label, route }) => (
                <li className='link' key={route}>
                  <Link href={route}>
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
            <section className="flex md:hidden">
              <div className="space-y-2" onClick={() => setIsNavOpen((prev) => !prev)}>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="w-6 h-6"
                  fill="white"
                  viewBox="0 0 24 24"
                  stroke="white"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M4 6h16M4 12h16M4 18h16"
                  />
                </svg>
              </div>
              <div className={isNavOpen ? "showMenuNav" : "hideMenuNav"}>
                <div
                  className="w-inherit absolute top-0 right-0 px-8 py-8 flex items-center justify-between cursor-pointer"
                  onClick={() => setIsNavOpen(false)}
                >
                  <Image
                    src='/images/logo.png'
                    alt='OpenWod Logo'
                    width={100}
                    height={100}
                  />
                  <svg
                    className="h-8 w-8 text-gray-600"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="white"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </div>
                <ul className="flex flex-col items-center justify-between min-h-[250px] text-white">
                  {links.map(({ label, route }) => (
                    <li className='link' key={route}>
                      <Link href={route} onClick={() => setIsNavOpen(false)}>
                        {label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </section>
          </nav>
          <style>{`
            .hideMenuNav {
              display: none;
            }
            .showMenuNav {
              display: block;
              position: absolute;
              width: 100%;
              height: 100vh;
              top: 0;
              left: 0;
              background: #1f1f1f;
              z-index: 10;
              display: flex;
              flex-direction: column;
              justify-content: space-evenly;
              align-items: center;
            }
          `}</style>
        </header>
        <section className='content'>
          <Toaster />
          {children}
        </section>
        <footer className='w-100 grid grid-cols-1 text-center bg-gray-300 p-5 gap-y-5 sticky top-[100vh]'>
          <div className='flex flex-col gap-x-5 gap-y-2 justify-center sm:flex-row'>
            <Link href={'/about'}>¿Quiénes somos?</Link>
            <Link href={'/faq'}>Preguntas frecuentes</Link>
            <Link href={'/'}>Estados financieros</Link>
            <Link href={'/'}>Factura electrónica</Link>
          </div>
          <div>
            <p>Dir. Bosque 2a Apartamento 302 Bloques del B 9, Ciudad de Maldonado, Uruguay</p>
            <p>Tel. 097111253</p>
          </div>
          <div className='flex flex-row gap-x-5 justify-center'>
            <Link href={'https://www.facebook.com'}>
              <BsFacebook size={30} />
            </Link>
            <Link href={'https://www.linkedin.com'}>
              <BsLinkedin size={30} target='_blank' />
            </Link>
            <Link href={'https://www.twitter.com'}>
              <BsTwitter size={30} />
            </Link>
          </div>
          <p>© 2023 OpenWord. Todos los derechos reservados.</p>
        </footer>
      </body>
    </html>
  )
}
