import Link from 'next/link';
import '../styles/globals.css'
import { Lexend } from 'next/font/google'

const inter = Lexend({ subsets: ['latin'] })

export const metadata = {
  title: 'Open Word - Landing Page',
  description: 'Generated by create next app',
};

const links = [
  { label: 'Home', route: '/' },
  { label: 'About', route: '/about' },
  { label: 'Contact', route: '/contact' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body className={inter.className}>
        <header>
          <h4>OpenWord</h4>
          <nav>
            <ul className='navigation'>
              {links.map(({ label, route }) => (
                <li className='link' key={route}>
                  <Link href={route}>
                    {label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <section className='content'>
          {children}
        </section>
      </body>
    </html>
  )
}
